# Generated by Django 4.0 on 2021-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tituloTag',
            field=models.CharField(default='Le Blogue', max_length=255),
        ),
    ]
