# Generated by Django 4.0 on 2021-12-16 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_rename_titulotag_post_titulo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechaPost',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(max_length=255),
        ),
    ]
