# Generated by Django 3.2.9 on 2022-01-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_auto_20220111_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='BlogDjango/images/default.jpg', null=True, upload_to='images/pfp/'),
        ),
    ]
