# Generated by Django 3.2.9 on 2022-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
